### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by nilswagner** [dfm/corner.py#133]
python3 demo.py
Traceback (most recent call last):
  File "demo.py", line 21, in <module>
    data1 = np.random.randn(ndim * 4 * nsamples / 5).reshape([4 * nsamples / 5,
  File "mtrand.pyx", line 1220, in numpy.random.mtrand.RandomState.randn
  File "mtrand.pyx", line 1377, in numpy.random.mtrand.RandomState.standard_normal
  File "_common.pyx", line 558, in numpy.random._common.cont
TypeError: 'float' object cannot be interpreted as an integer

**Comment by shbhuk** [comment]
Is your nsamples an integer?
