### ISSUE TITLE
Error on import, pandas incompatibility?

### ISSUE THREAD

**Issue by mdecleir** [dfm/corner.py#159]
Hello,

Today I noticed that I get an error when importing corner:

`import corner`

returns

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mdecleir/opt/anaconda3/envs/astroconda/lib/python3.7/site-packages/corner/__init__.py", line 6, in <module>
    from .corner import corner
  File "/Users/mdecleir/opt/anaconda3/envs/astroconda/lib/python3.7/site-packages/corner/corner.py", line 12, in <module>
    from .arviz_corner import arviz_corner
  File "/Users/mdecleir/opt/anaconda3/envs/astroconda/lib/python3.7/site-packages/corner/arviz_corner.py", line 9, in <module>
    from arviz.data import convert_to_dataset
  File "/Users/mdecleir/opt/anaconda3/envs/astroconda/lib/python3.7/site-packages/arviz/__init__.py", line 32, in <module>
    from .data import *
  File "/Users/mdecleir/opt/anaconda3/envs/astroconda/lib/python3.7/site-packages/arviz/data/__init__.py", line 2, in <module>
    from .base import CoordSpec, DimSpec, dict_to_dataset, numpy_to_data_array
  File "/Users/mdecleir/opt/anaconda3/envs/astroconda/lib/python3.7/site-packages/arviz/data/base.py", line 10, in <module>
    import xarray as xr
  File "/Users/mdecleir/opt/anaconda3/envs/astroconda/lib/python3.7/site-packages/xarray/__init__.py", line 12, in <module>
    from .core.combine import concat, auto_combine
  File "/Users/mdecleir/opt/anaconda3/envs/astroconda/lib/python3.7/site-packages/xarray/core/combine.py", line 11, in <module>
    from .merge import merge
  File "/Users/mdecleir/opt/anaconda3/envs/astroconda/lib/python3.7/site-packages/xarray/core/merge.py", line 10, in <module>
    PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
  File "/Users/mdecleir/opt/anaconda3/envs/astroconda/lib/python3.7/site-packages/pandas/__init__.py", line 244, in __getattr__
    raise AttributeError(f"module 'pandas' has no attribute '{name}'")
AttributeError: module 'pandas' has no attribute 'Panel'
```

I did not see this error before, and I am wondering whether a recent update to pandas might cause this problem?

**Comment by dfm** [comment]
Interesting - this is not directly a `corner` issue (it looks like it's actually an `xarray` issue that we get via `arviz`), but these dependencies were recently added. I'd recommend updating arviz (and probably pandas):

```bash
python -m pip install -U arviz pandas
```

If that doesn't fix the issue, please report the versions of everything that you can find (some of these will likely fail) and we'll go from there:

```bash
python -c 'import pandas; print(pandas.__version__)'
python -c 'import arviz; print(arviz.__version__)'
python -c 'import xarray; print(xarray.__version__)'
```

/cc @OriolAbril in case he's seen this over at ArviZ before.

**Comment by mdecleir** [comment]
Updating `xarray` solved the issue!
Thank you very much for your assistance!

FYI:
`python -c 'import pandas; print(pandas.__version__)'
1.2.3
python -c 'import arviz; print(arviz.__version__)'
0.11.2
python -c 'import xarray; print(xarray.__version__)'
0.17.0
`

**Comment by dfm** [comment]
Excellent - glad you got it working!

**Comment by mdecleir** [comment]
I think pandas and arviz were up to date, but I saw `xarray` was updated from 11 to 17...
